(function(){
'use strict';
const C=window.LMCore,V=window.LMOffice,$=id=>document.getElementById(id),money=n=>'$'+n.toFixed(2);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=localStorage;}catch(e){storage={getItem(){return null;},setItem(){throw Error('Storage unavailable');}};}
const store=new C.Store(storage),save=store.load(),audio=new GameAudio();audio.setMuted(save.muted);
const nav=new C.Nav(V.obstacles);
let modalMode='',returnModal='',previousUI='',last=0,uiTime=0;
const secondsLeft=e=>Math.ceil((1-e.urgency)*C.STATS[e.kind].patience*(g.day<=2?1.3:1)*(g.event.patience||1));
function saveNow(s){store.write(s);$('save-warning').hidden=store.ok;}
function sound(method){try{audio[method]?.();}catch(e){/* Audio is optional; gameplay stays available. */}}
const g=new C.Game(save,nav,{save:saveNow,message:showToast,pickup:()=>sound('ding'),seat:()=>sound('latch'),finish:()=>{sound('flush');sound('ding');},complaint:()=>sound('alert'),paper:()=>sound('latch'),restock:()=>sound('latch'),end:()=>report()});
window.__lineManager={game:g,nav,view:V,store};
function showToast(text){$('toast').textContent=text;$('toast').classList.add('show');}
function btn(label,action,cls='primary',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function sheet(html,wide=false,cls=''){const m=$('modal');m.innerHTML=`<section class="sheet ${wide?'wide':''} ${cls}" role="dialog" aria-modal="true" aria-label="${modalMode}">${html}</section>`;m.hidden=false;document.body.classList.add('menu');requestAnimationFrame(()=>m.querySelector('button:not(:disabled)')?.focus({preventScroll:true}));}
function closeModal(){modalMode='';$('modal').hidden=true;document.body.classList.remove('menu');previousUI='';}
function days(){return `<div class="seven-days">${Array.from({length:7},(_,i)=>`<button data-replay="${i+1}" aria-label="Replay Day ${i+1}" class="day-dot ${save.day===i+1?'active':''}" ${save.checkpoint||i+1>save.day?'disabled':''}>${i+1}<small>${'★'.repeat(save.records[i+1]?.stars||0)||'·'}</small></button>`).join('')}</div>`;}
const brand=()=>'<img class="brand-lockup" src="assets/poopprofit-logo-current.png" alt="Poop Profit. Find Out What You Make to Poop.">';
const mascot=()=>'<div class="mascot" role="img" aria-label="Herman Bowels"></div>';
function title(){modalMode='Welcome';g.screen='title';const cp=save.checkpoint,hasReport=save.lastReport;const label=cp?'Continue shift':hasReport?'View shift report':save.tutorialDone?'Play · Day '+save.day:'Start orientation';
 sheet(`${brand()}<div class="title-hero"><div><span class="eyebrow">LINE MANAGER · FACILITIES DIVISION</span><h1>Lead the line.<br><em>Run the floor.</em></h1><p>Escort the team. Keep the paper stocked. Put every break on the books.</p></div>${mascot()}</div><div class="preview-note">A very important job. A very fancy restroom.</div>${days()}<div class="records"><div><small>Best career shift</small><strong>${money(Math.max(0,...Object.values(save.records).map(r=>r.gdp||0)))}</strong></div><div><small>Today's best</small><strong>${money(save.daily[C.dateKey()]?.gdp||0)}</strong></div></div><div class="buttons">${btn(label+' <span aria-hidden="true">→</span>','continue')}${btn("Today's challenge",'daily','secondary')}${btn("Herman's field guide",'help','text-btn')}</div><p class="fine">3-minute shifts · Tap or click to play<br>Progress saves in this browser.</p>${store.recovered?'<p class="fine">Your available backup was checked while restoring progress.</p>':''}`,true,'title-sheet');
}
function brief(){modalMode='Shift briefing';g.screen='brief';const daily=g.mode==='daily',orient=g.mode==='orientation';const nextUnlock=g.day===1?'Leadership Seminar opens on Day 2.':g.day===2?'Heated Seat opens on Day 3.':g.day<7?'One more desk opens next day.':'First floor complete. Keep setting records in repeatable shifts.';
 sheet(`${brand()}<div class="brief-hero"><div><span class="eyebrow">${daily?'DAILY CHALLENGE · '+g.dailyKey:orient?'ORIENTATION':'DAY '+g.day+' · '+g.employees.length+' DESKS'}</span><h2>${orient?'Welcome to<br><em>Facilities.</em>':escape(g.event.name)}</h2></div>${mascot()}</div><p>${orient?'Learn by doing. Take two employees to a stall and refill the paper. There is no HR pressure during orientation.':escape(g.event.desc)}</p>${!orient?`<dl><div><dt>Bathroom GDP target</dt><dd>${money(g.target)}</dd></div><div><dt>Optional objective</dt><dd>${objectiveShort()}</dd></div><div><dt>Your line capacity</dt><dd>${g.leadCap} employees</dd></div></dl>`:''}<div class="preview-note">${daily?'Same daily setup for everyone. Your career budget and equipment stay separate.':orient?'Employees wait at their desks until you collect them.':nextUnlock}</div><div class="buttons">${btn(orient?'Start orientation':'Clock in','start')}${!daily&&!orient?btn('Facilities shop · '+save.budget+' credits','shop','secondary'):''}${btn('Back','home','secondary')}</div>`);
}
function objectiveShort(){return {group:'Lead 2 together',service:'Complete 8 breaks',streak:'4-break streak',clean:'4 breaks, no complaints'}[g.objective];}
function objectiveText(){return {group:'Escort at least two employees together',service:'Complete eight breaks',streak:'Complete four consecutive breaks without a complaint',clean:'Complete four breaks with no complaints'}[g.objective];}
function pause(){g.pause();modalMode='Shift paused';sheet(`<span class="eyebrow">TAKE YOUR TIME</span><h2>Office on hold.</h2><p>Your team can wait. The shift is paused.</p><div class="buttons">${btn('Back to the floor','resume')}${btn('How to play','help','secondary')}${btn('Save & main menu','home','secondary')}</div><p class="fine">Career shifts save their current positions and your current destination. Daily challenges restart when you leave them.</p>`);}
function guideIcon(kind){const paths={pickup:'<circle cx="20" cy="12" r="5"/><path d="M10 34V25q0-8 10-8t10 8v9M32 9l6-5M34 15h7"/>',seat:'<path d="M6 5v34M34 5v34M6 6h28M13 23h14q0 12-7 12t-7-12ZM20 35v5"/>',paper:'<rect x="9" y="9" width="23" height="28" rx="6"/><ellipse cx="20.5" cy="10" rx="11.5" ry="6"/><path d="M32 14v16h7M17 9h7"/>',move:'<circle cx="25" cy="8" r="4"/><path d="m12 24 9-10 9 8 8-2M21 15l-4 15-10 8M18 29l11 4v9M3 17h9M2 23h6"/>',star:'<path d="m22 4 5 12 13 1-10 9 3 13-11-7-12 7 3-13-10-9 14-1Z"/>'};return `<svg viewBox="0 0 44 44" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round">${paths[kind]}</svg>`;}
function help(){returnModal=modalMode;if(g.screen==='play')g.pause();modalMode='How to play';const steps=[['pickup','Pick up.','Tap a seated employee with a raised hand. Herman collects them at their desk.'],['seat','Escort.','Tap an open stall. Change stalls at any time. Tap another employee on the way to collect them first, then continue to your stall.'],['paper','Restock.','Tap Restock on an empty stall. Herman collects paper and refills that stall. Use Get paper to top up a dispenser early.'],['move','Change your mind.','Tap clear floor to change direction immediately. Your followers stay with you. Stop walking cancels the destination.'],['star','Keep it running.','Urgency continues in line. Three complaints end a shift. Complete breaks, earn stars, and spend Facilities credits on upgrades.']];sheet(`${brand()}<div class="guide-hero"><div><span class="eyebrow">HERMAN'S FIELD GUIDE</span><h2>A little direction.</h2><p>Keep the line moving. Make every break count.</p></div>${mascot()}</div><div class="legend">${steps.map((v,i)=>`<div><b>0${i+1}</b>${guideIcon(v[0])}<span><strong>${v[1]}</strong>${v[2]}</span></div>`).join('')}</div><p class="fine">Bathroom GDP is simulated on-the-clock earnings. Facilities credits are your upgrade budget.<br>Drag to pan. Pinch or scroll to zoom. Space or Escape pauses.</p><div class="buttons">${btn('Got it <span aria-hidden="true">→</span>','help-close','primary gold-button')}</div>`,true,'guide-sheet');}
function report(){modalMode='Shift report';g.screen='report';const r=g.report||save.lastReport;if(!r){title();return;}g.report=r;
 const advice=r.complaints?'Try grouping nearby requests and refilling before the rush.':r.breaks<8?'Collect your next employee while a stall is occupied.':'Good routing. Try a different upgrade or chase the next star.';
 sheet(`<span class="eyebrow">${r.mode==='daily'?'DAILY CHALLENGE':r.mode==='orientation'?'ORIENTATION COMPLETE':'DAY '+r.day} · SHAREHOLDER REPORT</span><h2>${r.mode==='orientation'?'You know the floor.':r.early?'HR called it a day.':r.stars===3?'Outstanding day, team.':'Another day on the books.'}</h2><div class="stars" aria-label="${r.stars} of 3 stars">${'★'.repeat(r.stars)}${'☆'.repeat(3-r.stars)}</div><div class="report-total">${money(r.gdp)}</div><span class="eyebrow">BATHROOM GDP</span><dl><div><dt>Breaks completed</dt><dd>${r.breaks}</dd></div><div><dt>HR complaints</dt><dd>${r.complaints} / 3</dd></div><div><dt>Best smooth-operation streak</dt><dd>${r.streak}</dd></div><div><dt>Optional objective</dt><dd>${r.goal?'Complete':'Try again'}</dd></div>${r.mode!=='daily'?`<div><dt>Facilities credits added</dt><dd class="gold">+${r.credited}</dd></div>`:''}</dl><p>${r.mode==='orientation'?'Herman is ready. Your first real shift awaits.':advice}</p>${r.mode==='career'&&r.credited<r.award?'<p class="fine">Replay rewards only add the improvement over your previous award for this day.</p>':''}<div class="buttons">${btn(r.mode==='daily'?'Try the challenge again':r.mode==='orientation'?'Open Day 1':'Facilities shop','report-next')}${r.mode==='career'?btn('Retry this shift','retry','secondary'):''}${btn('Main menu','home','secondary')}</div>`);
}
function shop(){modalMode='Facilities shop';g.screen='shop';const heat=C.heatPreview();
 sheet(`<span class="eyebrow">FACILITIES PROCUREMENT</span><h2>A better break room.</h2><div class="balance">${save.budget} Facilities credits available</div><div class="upgrade-list">${C.UPGRADES.map(u=>{const level=save.upgrades[u.id],price=u.prices[level],locked=save.day<u.day;return `<div class="upgrade"><span class="upgrade-icon">${u.icon}</span><div><h3>${u.name} ${level?'<small>· Level '+level+'</small>':''}</h3><p>${u.desc}</p></div><button data-buy="${u.id}" ${price===undefined||locked||save.budget<price?'disabled':''}>${locked?'Day '+u.day:price===undefined?'Maxed':price+' credits'}</button></div>`;}).join('')}</div>${save.upgrades.heat?`<p>Heated Seat location:</p><div class="heat-choices">${Array.from({length:2+save.upgrades.stall},(_,i)=>`<button data-heat="${i+1}" class="${save.heated===i+1?'selected':''}">Stall ${i+1}</button>`).join('')}</div>`:''}<p class="fine">Sales Rep comparison: ${heat.normalSeconds.toFixed(1)}s / ${money(heat.normalGDP)} normally; ${heat.heatedSeconds.toFixed(1)}s / ${money(heat.heatedGDP)} heated. Heated breaks count as two completions for the service portion of the Facilities award.</p><div class="buttons">${btn(save.lastReport?'Open tomorrow':'Return to briefing','shop-next')}${btn('Main menu','home','secondary')}</div>`,true);
}
function restoreReport(){const r=C.copy(save.lastReport);g.loadDay(r.mode,r.day);g.report=r;report();}
function doAction(action){sound('unlock');switch(action){
 case 'continue':if(save.checkpoint){g.restore();pause();}else if(save.lastReport)restoreReport();else{g.loadDay(save.tutorialDone?'career':'orientation',save.day);brief();}break;
 case 'daily':g.loadDay('daily',7);brief();break;
 case 'start':closeModal();g.begin();V.fit();if(g.mode==='orientation')V.focus(3.5,7.4);break;
 case 'resume':closeModal();g.screen='play';break;
 case 'home':if(g.screen==='play'||g.screen==='pause')g.persist();title();break;
 case 'help':help();break;
 case 'help-close':if(returnModal==='Welcome')title();else if(returnModal==='Shift briefing')brief();else pause();break;
 case 'shop':shop();break;
 case 'report-next':if(g.mode==='daily'){g.loadDay('daily',7);brief();}else if(g.mode==='orientation'){g.next();brief();}else shop();break;
 case 'retry':{const mode=g.mode,day=g.day;save.lastReport=null;g.loadDay(mode,day);saveNow(save);brief();break;}
 case 'shop-next':if(save.lastReport){g.report=save.lastReport;g.mode=save.lastReport.mode;g.day=save.lastReport.day;g.next();}else g.loadDay('career',save.day);brief();break;
 }update();}
$('modal').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.replay){save.lastReport=null;g.loadDay('career',Number(b.dataset.replay));saveNow(save);brief();}if(b.dataset.action)doAction(b.dataset.action);if(b.dataset.buy){if(g.buy(b.dataset.buy))sound('ding');shop();}if(b.dataset.heat){save.heated=Number(b.dataset.heat);saveNow(save);shop();}});
$('modal').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const list=[...$('modal').querySelectorAll('button:not(:disabled)')];if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
$('pause').onclick=pause;$('help').onclick=help;
$('sound').onclick=()=>{sound('unlock');save.muted=!save.muted;audio.setMuted(save.muted);saveNow(save);$('sound').textContent=save.muted?'♫̸':'♪';$('sound').setAttribute('aria-label',save.muted?'Enable sound':'Mute sound');};
$('view-fit').onclick=()=>V.fit();$('zoom-in').onclick=()=>V.zoomBy(1.2);$('zoom-out').onclick=()=>V.zoomBy(1/1.2);
$('cancel').onclick=()=>{g.cancel();update();};
function command(kind,id){sound('unlock');g.enqueue(kind,id);update();}
V.onTap(c=>command(c.kind,c.id));
$('paper').onclick=()=>command('paper');
$('roster').addEventListener('click',e=>{const b=e.target.closest('[data-employee]');if(b)command('pickup',b.dataset.employee);});
$('stalls').addEventListener('click',e=>{const b=e.target.closest('[data-stall]');if(b)command('stall',Number(b.dataset.stall));});
addEventListener('keydown',e=>{if(e.code==='Space'&&e.target.tagName==='BUTTON')return;if(e.code==='Space'||e.key==='Escape'){e.preventDefault();if(g.screen==='play')pause();else if(modalMode==='Shift paused')doAction('resume');}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.screen==='play')pause();});addEventListener('pagehide',()=>g.persist());
function update(){
 $('day-label').textContent=g.mode==='orientation'?'ORIENTATION':g.mode==='daily'?'DAILY CHALLENGE':'DAY '+g.day+' · '+g.event.name.toUpperCase();
 const min=Math.min(17*60,9*60+Math.floor(g.clock/g.duration*480)),hr=Math.floor(min/60);$('time-label').textContent=`${(hr+11)%12+1}:${String(min%60).padStart(2,'0')} ${hr>=12?'PM':'AM'}`;
 $('time-progress').style.width=Math.min(100,g.clock/g.duration*100)+'%';$('gdp').textContent=money(g.gdp);$('target').textContent='Target '+money(g.target);$('breaks').textContent=g.breaks+' breaks';$('streak').textContent=g.streak>=2?g.streak+' in a row · +4 credits every 3':'Build a smooth operation';$('hr').textContent='● '.repeat(g.complaints)+'○ '.repeat(3-g.complaints);$('hr').style.color=g.complaints?'var(--red)':'var(--green)';$('hr-note').textContent=g.complaints===2?'One more closes the office':'Keep the team comfortable';
 $('line-count').textContent='LINE '+g.followers.length+' / '+g.leadCap;
 const c=g.active,queued=g.queue.length;$('route').textContent=c?(c.kind==='pickup'?'Collecting '+(g.employees.find(e=>e.id===c.id)?.name||'employee'):c.kind==='stall'?'Heading to stall '+c.id:c.kind==='paper'?'Collecting paper':'Walking')+(queued?' · then stall '+g.queue[0].id:''):'Tap an employee who needs a break';
 $('cancel').disabled=!c&&!queued;
 const needing=g.employees.filter(e=>e.state==='needing');
 const html=needing.length?needing.map(e=>{const q=g.active?.id===e.id||g.queue.some(c=>c.id===e.id);return `<button class="employee-btn ${e.urgency>.72?'urgent':''} ${q?'queued':''}" data-employee="${e.id}" aria-label="Pick up ${e.name}${q?', collecting':''}"><strong>${e.name}${q?' · collecting':''}</strong><small>${C.STATS[e.kind].label} · ${secondsLeft(e)}s</small><i style="width:${Math.round(e.urgency*100)}%"></i></button>`;}).join(''):`<div class="empty">${g.followers.length?'Your team is in line. Tap an open stall.':g.mode==='orientation'?'Wait for a request. Herman is ready.':'All requests handled. Time to check the paper.'}</div>`;
 // Update urgency without replacing a focused button between pointerdown and click.
 const key=needing.map(e=>e.id+':'+(g.active?.id===e.id||g.queue.some(c=>c.id===e.id))).join('|');if(previousUI!==key||!$('roster').firstChild){$('roster').innerHTML=html;previousUI=key;}else if(needing.length){for(const e of needing){const b=$('roster').querySelector(`[data-employee="${e.id}"]`);if(b){b.querySelector('i').style.width=Math.round(e.urgency*100)+'%';b.classList.toggle('urgent',e.urgency>.72);b.querySelector('small').textContent=C.STATS[e.kind].label+' · '+secondsLeft(e)+'s';}}}else $('roster').firstChild.textContent=g.followers.length?'Your team is in line. Tap an open stall.':'All requests handled. Time to check the paper.';
 if($('stalls').children.length!==g.stalls.length)$('stalls').innerHTML=g.stalls.map(s=>`<button data-stall="${s.i}" class="stall-btn"><b></b><small></small></button>`).join('');
 for(const s of g.stalls){const b=$('stalls').querySelector(`[data-stall="${s.i}"]`);b.className=`stall-btn ${s.occupant?'busy':''} ${!s.paper?'empty-paper':''}`;b.setAttribute('aria-label',`Stall ${s.i}, ${s.occupant?'occupied':s.paper?'open':'out of paper'}`);b.querySelector('b').textContent=(!s.paper?'Restock ':s.heated?'≈ Stall ':'Stall ')+s.i;b.querySelector('small').textContent=!s.paper?'Get paper + refill':s.occupant?'Occupied':s.paper+' / '+g.paperMax+' paper';}
 $('paper').classList.toggle('carrying',g.herman.carrying);$('paper').querySelector('strong').textContent=g.herman.carrying?'Paper in hand':'Get paper';$('paper').querySelector('small').textContent=g.herman.carrying?'Tap a stall':'Supply shelf';
 $('objective').textContent=g.mode==='orientation'?'ORIENTATION · '+['Pick up Jamie','Escort Jamie to a stall','','Collect paper and refill the empty stall','Escort Riley to a stall'][g.instruction]:(g.goalMet?'✓ COMPLETE':'OPTIONAL')+' · '+objectiveText();
 const lesson=$('lesson');lesson.hidden=g.mode!=='orientation'||g.screen!=='play';
 if(!lesson.hidden){const text=g.instruction===0?'Tap Jamie’s raised hand or name to collect them.':g.instruction===1?'Tap an open stall. Herman will escort Jamie there.':g.instruction===3?(g.herman.carrying?'Tap the empty stall to refill its dispenser.':'Tap Get paper to collect a fresh roll.'):'Collect Riley, then tap an open stall.';lesson.querySelector('p').textContent=text;lesson.querySelector('strong').textContent=g.instruction===0?'01 · Pick up':g.instruction===1?'02 · Escort':g.instruction===3?'03 · Restock':'04 · Your turn';}
 if(g.messageTime<=0)$('toast').classList.remove('show');
}
function frame(t){const dt=last?Math.min(.1,(t-last)/1000):0;last=t;g.tick(dt);V.render(g,t/1000);uiTime+=dt;if(uiTime>.1){update();uiTime=0;}requestAnimationFrame(frame);}
const imgs=Object.values(V.images);Promise.all(imgs.map(i=>i.decode().catch(()=>{}))).then(()=>{$('loading').hidden=true;title();update();requestAnimationFrame(frame);}).catch(()=>{$('load-status').textContent='The office could not load. Please refresh.';});
})();
